### ISSUE TITLE
String rephrasing

### ISSUE THREAD

**Issue by jt15s** [humdingerb/MidiSynth#5]
I've been translating MidiSynth to Polyglot and noticed one of the strings was a bit strange in phrasing. I think it needs to be changed to allow users to better understand what the application is saying.

The string is located under "Application" and reads "This **is no valid** key map file.". It should probably be changed to "This **is an invalid** key map file." to make it clearer that the key map file is invalid to the user.

Thanks!

**Comment by humdingerb** [comment]
I went with "This isn't a valid key map file", because it may not even be an invalid key map file, but no key map file at all. :)
